CREATE TABLE DIRETOR (
    ID INT AUTO_INCREMENT NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)

);

CREATE TABLE FILME (
    ID INT AUTO_INCREMENT NOT NULL,
    TITULO VARCHAR(250) NOT NULL,
    ID_DIRETOR INT,
    PRIMARY KEY (ID),
    FOREIGN KEY (ID_DIRETOR) REFERENCES DIRETOR (ID)
);
