CREATE TABLE DIRETOR (
    ID INT AUTO_INCREMENT NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE ATOR (
    ID INT AUTO_INCREMENT NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE FILME (
    ID INT AUTO_INCREMENT NOT NULL,
    TITULO VARCHAR(250) NOT NULL,
    ID_DIRETOR INT,
    PRIMARY KEY (ID),
    FOREIGN KEY (ID_DIRETOR) REFERENCES DIRETOR (ID)
);

CREATE TABLE FILME_ATOR (
    ID_FILME INT NOT NULL,
    ID_ATOR INT NOT NULL,
    PRIMARY KEY (ID_FILME, ID_ATOR),
    FOREIGN KEY (ID_FILME) REFERENCES FILME (ID),
    FOREIGN KEY (ID_ATOR) REFERENCES ATOR (ID)
);
